print('Instructions:\nType one of the capitalized words, but beware, your choice will determine your fate!')
print('You may type "LEAVE" at anytime if you do not with to continue.')
print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
print('You and your friends Jake and Lisa have been planning a visit to the abandoned house on the edge of town for weeks.')
print('There have been rumors going around that it is haunted, and tonight you all finally found the courage to see if the rumors were true.')
print('At a quarter to midnight, you meet your friends outside the house. The second you get off your bike, you hear a loud crash inside the house,')
print('as if something very large had been shoved over. Everybody jumps and looks at the dark house, waiting, but there are no other sounds.')
enter = input('You look at your friends and discuss wether you should still ENTER or just LEAVE because something could actually be inside. ')
if enter.lower() != 'enter':
    print('\nYou feel your pounding heart pumping the fear through your veins. You could not do this. Without a second thought you and your friends hopped on your bikes and rode back to your homes, never to return.')
    print('\nThe end.')
    print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
else:
    print('\nEveryone is feeling determined to explore this house, so you gather your courage, walk up the steps and slowly creak open the front door.')
    direction = input('Brave Jake walks in first and shines his flashlight around. We discover a staircase STRAIGHT ahead, and doors to the LEFT and RIGHT. ')
    if direction.lower() == 'straight':
        print('\nYou start walking towards the stairs and as you pass the doors on either side Lisa says we should SPLIT UP to cover more ground faster. ')
        split = input('You think that is a terrible idea and that you should STICK TOGETHER because that is safer. ')
        if split.lower() == 'split up':
            print('\nLisa wants to leave as soon as possible so you all split up. Lisa goes right, Jake goes left, and you hesitantly go up stairs.')
            print('You explore the entire upstairs and find nothing startling, so you start to head back but find no stairs where you came up.')
            print('You explore everything again and find no way out of the house, all of the windows are even boarded up. You try calling your friends,')
            print('but there is no signal. You pound and shout at walls, and try to break out, but with no sucess. You never saw your friends again,')
            print('and you slowly were driven into madness as you slowly died of starvation.')
            print('Never split up.')
            print('The end.')
            print('------------------------------------------------------------------------------------------------------------------------------------------------------------------')
        elif split.lower() == 'stick together':
            print('\nEveryone agrees that sticking together is safer, so you all go up the stairs together. As you walk up, the old boards creak loud enough')
            print('to alert the entire house that you are there. You discover a long hallway at the top of the staircase with two doors on each side.')
            print('The last door at the end of the hall starts to slowly open and a dark figure starts to walk out of it. Jake moves to HIDE in the first door')
            hide = input('on the right, but Lisa is frozen in terror. You stand with her and WATCH as two more figures enter the hallway. ')
            if hide.lower() == 'hide':
                print('\nYou drag Lisa into the room with Jake and slam shut, and barricade the door. You all are panting in the dark room as you hear shuffling')
                print('outside the door. Little did you know, there was another doorway in that room that connected to the other room leading to the hallway.')
                print('After everything is quiet, Jake scans the room with flashlight and finds three zombies by the other door in the room staring right at you')
                print('Everyone screams as they lunge at you and bite you and your friends until you all become zombies to haunt the house forever.')
                print('The end.')
                print('------------------------------------------------------------------------------------------------------------------------------------------------------------------')
            elif hide.lower() == 'watch':
                print('\nFear has frozen you and Lisa, you can not move as the three figures slowly got closer and closer, but all of a sudden you hear')
                print('a familiar voice say "Lisa?" It is one of Lisas class mates and her two friends who also decided to explore the "haunted house" that night.')
                print('They tell you that they were the ones that accidentally knocked over a lamp earlier. You all laugh and find Jake and explain what happened,')
                print('and then exit the front door, no more in fear of the old abandoned house at the edge of town.')
                print('The end.')
                print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
            else:
                print('\nYou leave Lisa and Jake upstairs and sprint out of the house, but after waiting one, and then five, and then fifteen minutes,')
                print('you still have not heard anything and nobody else has left the house. So you call the police who arrive 15 minutes later,')
                print('and search the entire house, but find none of your friends, or and strange shadow figures. You never see your frinds again.')
                print('The end.')
                print('------------------------------------------------------------------------------------------------------------------------------------------------------------------')
        else:
            print('\nAnother crash sounds above you and you all jump again and run out of the house, scared for your lives. Maybe you will come back another time.')
            print('The end.')
            print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
    elif direction.lower() == 'right':
        print('\nYou slowly walk down the hallway and enter the right doorway to find a large dusty living room with furniture covered in white sheets.')
        print('To the right you see a beautiful fireplace between 2 windows, and to the left another dark doorway that Jake is starting to walk towards.')
        print('As you and Lisa walk up to the fireplace, you notice dust falling down from the chimney. Suddenly, you hear thumping and screeching from inside,')
        fight = input('and a large creature crashes down in a cloud of dust. You turn to RUN but notice an iron stoker by the fireplace and debate grabbing it to FIGHT. ')
        if fight.lower() == 'fight':
            print('\nYou snatch up the stoker and face the creature, prepared to fight. It lunges at you with sharp teeth wide open and ready to bite, but you are ready.')
            explore = input('You stab the creature right in the mouth and throw it against the wall. Jake and Lisa come over to EXPLORE the creature, but you think you should LEAVE. ')
            if explore.lower() == 'explore':
                print('\nYou decide to approach the creature to figure out what it is. Jake pulls out the stoker from its mouth and starts poking its talons when it suddenly jumps up!')
                print('It wasnt dead! It ripps the stoker from Jakes hands and howls, two other creatures come in from behind you and simultaneously jump on you and eat all of you alive. ')
                print('\nThe end.')
                print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
            else:
                print('\nYou grab both your friends by their arms and drag them out of the house telling them you need to leave in case there were other creatures in the house.')
                print('Sure enough, as soon as you got on your bikes you hear howling of multiple creatures inside the house so you ride your bikes home faster than you have ever riden before.')
                print('The end.')
                print('-------------------------------------------------------------------------------------------------------------------------------------------------------------------')
        else:
            print('\nYou start running as fast as you can but notice out of the corner of your eye the creature had caught up to Lisa. You hear her scream')
            print('as she is tripped and then dragged up the fireplace. Another creature came out of the doorway by Jake and caught him before he could run to safety.')
            print('You run for your life out of the living room as Jake is dragged into that dark room, shouting for help. You run out the front door and start calling 911.')
            print('Almost to your bike, the police answer, but another creature lands on your back, collapsing you to the ground and sending your phone flying.')
            print('As everything fades to black, you pray that help will arrive before its too late.')
            print('The end.')
            print('-----------------------------------------------------------------------------------------------------------------------------------------------------------------')
    elif direction.lower() == 'left':
        print('\nYou slowly walk down the hallway and enter the left doorway to find a dirty little kitchen with a dining room on the other side.')
        explore = input('Jake wonders if theres any food so he starts to EXPLORE, but Lisa says we should CHECK the diningroom first to make sure its safe. ')
        if explore.lower() == 'explore':
            print('\nJake says he is hungry so we start checking the cabinets and drawers and find nothing but old dusty dishes and spider webs.')
            print('You go to check the old refrigerator and as soon as you open the door, giant spiders pour out all over the foor and start climbing up your legs.')
            print('You scream and try to run away as the spiders start biting you all over, but their poison is too strong, you are starting to go numb.')
            print('Jake and lisa try to help pull you away but the spiders started covering them and biting them as well. The last thing you see before you are covered in webs')
            print('is your friends going limp and collapsing and being covered in spiders.')
            print('The end.')
            print('------------------------------------------------------------------------------------------------------------------------------------------------------------------')
        elif explore.lower() == 'check':
            print('\nYou think its a good idea to secure the area so you check the dining room and find nothing startling. You go back into the hallway,')
            print('and check the room on the right to find it lifeless as well, so you all decide to slowly head up the stairs to find what made the crash.')
            print('You slowly creep up the stairs and discover a long hallway at the top of the staircase that has two closed doors on either side.')
            print('The last door at the end of the hall starts to slowly open and a dark figure starts to walk out of it. Jake moves to HIDE in the first door')
            hide = input('on the right, but Lisa is frozen in terror. You stand with her and WATCH as two more figures enter the hallway. ')
            if hide.lower() == 'hide':
                print('\nYou drag Lisa into the room with Jake and slam shut, and barricade the door. You all are panting in the dark room as you hear shuffling')
                print('outside the door. Little did you know, there was another doorway in that room that connected to the other room leading to the hallway.')
                print('After everything is quiet, Jake scans the room with flashlight and finds three zombies by the other door in the room staring right at you')
                print('Everyone screams as they lunge at you and bite you and your friends until you all become zombies to haunt the house forever.')
                print('The end.')
                print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
            elif hide.lower() == 'watch':
                print('\nFear has frozen you and Lisa, you can not move as the three figures slowly got closer and closer, but all of a sudden you hear')
                print('a familiar voice say "Lisa?" It is one of Lisas class mates and her two friends who also decided to explore the "haunted house" that night.')
                print('They tell you that they were the ones that accidentally knocked over a lamp earlier. you all laugh and find Jake and explain what happened,')
                print('and then exit the front door, no more in fear of the old abandoned house at the edge of town.')
                print('The end.')
                print('------------------------------------------------------------------------------------------------------------------------------------------------------------------')
            else:
                print('\nYou leave Lisa and Jake upstairs and sprint out of the house, but after waiting one, and then five, and then fifteen minutes,')
                print('you still have not heard anything and nobody else has left the house. So you call the police who arrive 15 minutes later,')
                print('and search the entire house, but find none of your friends, or and strange shadow figures. You never see your frinds again.')
                print('The end.')
                print('------------------------------------------------------------------------------------------------------------------------------------------------------------------')
        else:
            print('\nThe hairs on the back of your neck stand up as something invisble passes through you. Your friends felt it as well, so with out saying as word,')
            print('you all hurry out of the house and go home and continue spreading the rumor that the house is haunted.')
            print('The end')
            print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
    else:
        print('\nYou hear footsteps creaking the floorboards above so you all turn around and sprint out of the house never to return.')
        print('The end.')
        print('----------------------------------------------------------------------------------------------------------------------------------------------------------------')
    # else:
    #     while direction.lower != 'straight' or 'right' or 'left':
    #         direction = input('\nPlease type "straight", "right", "left", or "leave". ')
    #         exit()
