print('Hello!')
print()
first_name = input('What is your first name? ')
print('Hi ' + first_name.capitalize())
print()
last_name = input('What is your last name? ')
# print('Nice to meet you ' + first_name.capitalize() + ' ' + last_name.capitalize())
name = first_name + ' ' + last_name
print(f'Nice to meet you {name.title()}')
print()
color = input('What is your favorite color? ')
print('Wow' , first_name.capitalize() , 'your favorite color is' , (color))
print('I like that color too :)')
print()