print('Please enter the following information:')
first_name = input('First name: ')
last_name = input('Last name: ')
email = input('Email address: ')
phone = input('Phone number: ')
job = input('Job title: ')
id = input('ID number: ')
hair = input('Hair color: ')
eye = input('Eye color: ')
month = input('Month started: ')
training = input('Have you completed training? (yes or no) ')
print()
print('The card ID is:')
print('-----------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()}')
print((job.title()))
print('ID:' , (id))
print()
print((email.lower()))
print((phone))
print()
print(f'Hair: {hair.capitalize():11} Eyes: {eye.capitalize()}')
print(f'Month: {month.capitalize():10} Training: {training.capitalize()}')
print('-----------------------------------')